In [1]:
#@title
!pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.9-py2.py3-none-any.whl (12 kB)
Collecting tqdm==4.56.0
  Downloading tqdm-4.56.0-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 454 kB/s
Collecting numpy==1.19.1
  Downloading numpy-1.19.1-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 8.6 MB/s
Collecting lightgbm==2.3.1
  Downloading lightgbm-2.3.1-py2.py3-none-manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 19.6 MB/s
Collecting pytest==5.4.3
  Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
     |████████████████████████████████| 248 kB 50.1 MB/s
Collecting pandas==1.0.5
  Downloading pandas-1.0.5-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 39.6 MB/s
Collecting PyYAML==5.3.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 52.4 MB/s
Collecting xgboost==1.1.1
  Downloading xgboost-1.1.1-py3-none-manylinux2010_x86_64.whl (127.6 MB)
     |████████████████████████████████| 127.6 MB 15 kB/s
Requirement already satisfied: six==1.15.0 in /usr/local/lib/python3.7/dist-packages (from lazypredict) (1.15.0)
Requirement already satisfied: click==7.1.2 in /usr/local/lib/python3.7/dist-packages (from lazypredict) (7.1.2)
Collecting scikit-learn==0.23.1
  Downloading scikit_learn-0.23.1-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 33.9 MB/s
Collecting joblib==1.0.0
  Downloading joblib-1.0.0-py3-none-any.whl (302 kB)
     |████████████████████████████████| 302 kB 49.0 MB/s
Collecting scipy==1.5.4
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 12.8 MB/s
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas==1.0.5->lazypredict) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from pandas==1.0.5->lazypredict) (2.8.2)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (8.12.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (21.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (21.4.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (1.11.0)
Requirement already satisfied: importlib-metadata>=0.12 in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (4.10.1)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->lazypredict) (0.2.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.1->lazypredict) (3.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.12->pytest==5.4.3->lazypredict) (3.7.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.12->pytest==5.4.3->lazypredict) (3.10.0.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->pytest==5.4.3->lazypredict) (3.0.7)
Building wheels for collected packages: PyYAML
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=44636 sha256=aabf1424ae1cbfc3667168c1e1c11436578edb67ac96d3f7ebbd0df7108bd70d
  Stored in directory: /root/.cache/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
Successfully built PyYAML
Installing collected packages: numpy, scipy, joblib, scikit-learn, pluggy, xgboost, tqdm, PyYAML, pytest, pandas, lightgbm, lazypredict
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: pluggy
    Found existing installation: pluggy 0.7.1
    Uninstalling pluggy-0.7.1:
      Successfully uninstalled pluggy-0.7.1
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.62.3
    Uninstalling tqdm-4.62.3:
      Successfully uninstalled tqdm-4.62.3
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: pytest
    Found existing installation: pytest 3.6.4
    Uninstalling pytest-3.6.4:
      Successfully uninstalled pytest-3.6.4
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 2.2.3
    Uninstalling lightgbm-2.2.3:
      Successfully uninstalled lightgbm-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.0.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed PyYAML-5.3.1 joblib-1.0.0 lazypredict-0.2.9 lightgbm-2.3.1 numpy-1.19.1 pandas-1.0.5 pluggy-0.13.1 pytest-5.4.3 scikit-learn-0.23.1 scipy-1.5.4 tqdm-4.56.0 xgboost-1.1.1

In [10]:
!pip uninstall scikit-learn -y
!pip install scikit-learn==0.23.1

Found existing installation: scikit-learn 0.23.1
Uninstalling scikit-learn-0.23.1:
  Successfully uninstalled scikit-learn-0.23.1
Collecting scikit-learn==0.23.1
  Using cached scikit_learn-0.23.1-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.1) (1.19.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.1) (3.0.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.1) (1.5.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.1) (1.0.0)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.
Successfully installed scikit-learn-0.23.1

In [ ]:
#@title
!pip uninstall pandas
!pip install pandas
!pip install pandas --upgrade

Found existing installation: pandas 1.0.5
Uninstalling pandas-1.0.5:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/pandas-1.0.5.dist-info/*
    /usr/local/lib/python3.7/dist-packages/pandas/*
Proceed (y/n)? N
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.0.5)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.0.5)
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 23.5 MB/s
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.5
    Uninstalling pandas-1.0.5:
      Successfully uninstalled pandas-1.0.5

In [1]:
import lazypredict
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn import preprocessing

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)

In [2]:
from sklearn.model_selection import cross_val_score, GridSearchCV, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_curve, precision_recall_curve, auc, make_scorer, recall_score, accuracy_score, precision_score, confusion_matrix,balanced_accuracy_score,f1_score
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
import pandas as pd

In [3]:
dataset_train_boruta_NoOUT =  pd.read_csv("dataset_train_famd_NoOUT.csv")
dataset_test_boruta_NoOUT =  pd.read_csv("dataset_test_famd_NoOUT.csv")

In [4]:
dataset_train_boruta_NoOUT = dataset_train_boruta_NoOUT.drop(labels='Unnamed: 0', axis=1)
dataset_test_boruta_NoOUT = dataset_test_boruta_NoOUT.drop(labels='Unnamed: 0', axis=1)
dataset_train_boruta_NoOUT = dataset_train_boruta_NoOUT.drop(labels='X', axis=1)
dataset_test_boruta_NoOUT = dataset_test_boruta_NoOUT.drop(labels='X', axis=1)

In [5]:
dataset_train_boruta_NoOUT

      Dim.1  Dim.2  Dim.3  Dim.4  Dim.5  ...  Dim.36  Dim.37  Dim.38  Dim.39  LET_IS
0      1.34   2.71   1.93  -0.35  -1.27  ...    0.05    2.27    0.12   -0.64       0
1     -2.48  -2.05   0.82   0.94  -0.62  ...   -0.54   -0.36    0.19    0.30       0
2     -2.39   0.31   1.05   0.76   0.39  ...    0.62   -0.53   -0.84   -0.36       0
3     -1.09  -0.41   0.82  -1.21   0.83  ...    0.71    0.51    0.35   -0.22       0
4     -1.19   0.95   1.87   1.52   0.21  ...    0.17   -0.23   -0.92   -0.58       0
...     ...    ...    ...    ...    ...  ...     ...     ...     ...     ...     ...
1334   1.16   0.46  -1.72  -1.54   0.50  ...    1.84   -1.04   -1.37    0.92       1
1335  -0.61  -2.06   1.47   2.07   1.25  ...    0.81   -0.56   -0.35    1.38       1
1336   3.26   0.95   2.82   0.27  -2.30  ...    1.31   -0.27   -0.28   -0.25       1
1337  -1.62  -1.14   1.47   1.29   0.57  ...   -1.05   -0.68   -0.49   -0.18       1
1338   4.54  -3.66  -4.39   0.02  -0.87  ...    1.02    0.39    0.12    0.02       1

[1339 rows x 40 columns]

In [6]:
#X = data4

#X=X.drop(["LET_IS"], axis = 1)
#X_standardized = preprocessing.scale(X)
#y = data4["LET_IS"]

#X_train, X_test, y_train, y_test = train_test_split(X_standardized, y, test_size=0.2, random_state=1)

X_train = dataset_train_boruta_NoOUT.drop(["LET_IS"], axis = 1)
y_train = dataset_train_boruta_NoOUT["LET_IS"]
X_test = dataset_test_boruta_NoOUT.drop(["LET_IS"], axis = 1)
y_test = dataset_test_boruta_NoOUT["LET_IS"]

clf = LazyClassifier()
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

100%|██████████| 29/29 [00:05<00:00,  5.52it/s]

In [8]:
models

                               Accuracy  ...  Time Taken
Model                                    ...
NearestCentroid                    0.91  ...        0.03
PassiveAggressiveClassifier        0.86  ...        0.03
QuadraticDiscriminantAnalysis      0.87  ...        0.03
SGDClassifier                      0.90  ...        0.04
DecisionTreeClassifier             0.88  ...        0.13
LinearDiscriminantAnalysis         0.92  ...        0.04
AdaBoostClassifier                 0.91  ...        0.46
LogisticRegression                 0.91  ...        0.04
Perceptron                         0.87  ...        0.03
LinearSVC                          0.91  ...        0.15
XGBClassifier                      0.91  ...        0.61
BaggingClassifier                  0.90  ...        0.53
CalibratedClassifierCV             0.91  ...        0.52
LGBMClassifier                     0.91  ...        0.64
RidgeClassifier                    0.91  ...        0.03
RidgeClassifierCV                  0.91  ...        0.04
GaussianNB                         0.83  ...        0.02
SVC                                0.91  ...        0.13
ExtraTreeClassifier                0.86  ...        0.02
RandomForestClassifier             0.91  ...        0.92
ExtraTreesClassifier               0.90  ...        0.29
LabelPropagation                   0.84  ...        0.16
LabelSpreading                     0.84  ...        0.20
KNeighborsClassifier               0.87  ...        0.07
BernoulliNB                        0.84  ...        0.02
DummyClassifier                    0.76  ...        0.02

[26 rows x 5 columns]

In [9]:
for col in X_test:
  X_test[col] = X_test[col].astype(float)
  X_train[col] = X_train[col].astype(float)

In [10]:
mlp_g = {
    "hidden_layer_sizes": [(82,),(84,),(86,),(88,),(90,),(92,),(94,),(96)]
}

scorers_mlp = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score),
    'balanced_accuracy': make_scorer(balanced_accuracy_score),
    'f1': make_scorer(f1_score)
}

skf = StratifiedKFold(n_splits=5, random_state = 549)
refit_score='recall_score'

mlp_gsCV = GridSearchCV(
    MLPClassifier(activation = "tanh", solver = "adam", learning_rate = "adaptive", random_state= 123),
    mlp_g,
    scoring=scorers_mlp,
    refit=refit_score,
    cv = skf
)

mlp_gsCV.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=549, shuffle=False),
             estimator=MLPClassifier(activation='tanh',
                                     learning_rate='adaptive',
                                     random_state=123),
             param_grid={'hidden_layer_sizes': [(82,), (84,), (86,), (88,),
                                                (90,), (92,), (94,), 96]},
             refit='recall_score',
             scoring={'accuracy_score': make_scorer(accuracy_score),
                      'balanced_accuracy': make_scorer(balanced_accuracy_score),
                      'f1': make_scorer(f1_score),
                      'precision_score': make_scorer(precision_score),
                      'recall_score': make_scorer(recall_score)})

In [11]:
mlp_results = pd.DataFrame(mlp_gsCV.cv_results_)
mlp_results = pd.DataFrame(mlp_gsCV.cv_results_)[["param_hidden_layer_sizes","mean_test_precision_score", "mean_test_recall_score","mean_test_accuracy_score","mean_test_balanced_accuracy", 'mean_test_f1']]
mlp_results

  param_hidden_layer_sizes  ...  mean_test_f1
0                    (82,)  ...          0.61
1                    (84,)  ...          0.61
2                    (86,)  ...          0.64
3                    (88,)  ...          0.62
4                    (90,)  ...          0.62
5                    (92,)  ...          0.61
6                    (94,)  ...          0.63
7                       96  ...          0.62

[8 rows x 6 columns]

In [12]:
mlp = MLPClassifier(hidden_layer_sizes = (84,), activation = "tanh", solver = "adam", learning_rate = "adaptive", random_state= 123)
mlp_model = mlp.fit(X_train, y_train)
y_pred_mlp  = mlp_model.predict(X_test)


print("MLP:")
print("acc",accuracy_score(y_test, y_pred_mlp))
print("bacc",balanced_accuracy_score(y_test, y_pred_mlp))
print("precision",precision_score(y_test, y_pred_mlp))
print("sensitivity/recall",recall_score(y_test, y_pred_mlp))
print("specificity",balanced_accuracy_score(y_test, y_pred_mlp)*2-recall_score(y_test, y_pred_mlp))
print("fi",f1_score(y_test, y_pred_mlp))

MLP:
acc 0.9161676646706587
bacc 0.7897872930090764
precision 0.7948717948717948
sensitivity/recall 0.6078431372549019
specificity 0.9717314487632508
fi 0.6888888888888889

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_g = {
    "criterion": ["gini", "entropy"],
    "max_depth": [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,35]

}

scorers_dt = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score),
    'balanced_accuracy': make_scorer(balanced_accuracy_score),
    'f1': make_scorer(f1_score)
}

skf = StratifiedKFold(n_splits=5, random_state = 549)
refit_score='recall_score'

dt_gsCV = GridSearchCV(
    DecisionTreeClassifier(random_state=123),
    dt_g,
    scoring=scorers_dt,
    refit=refit_score,
    cv = skf
)

dt_gsCV.fit(X_train, y_train)
dt_results = pd.DataFrame(dt_gsCV.cv_results_)

In [ ]:
dt_results = pd.DataFrame(dt_gsCV.cv_results_)  
dt_results = pd.DataFrame(dt_gsCV.cv_results_)[["param_criterion","param_max_depth","mean_test_precision_score", "mean_test_recall_score","mean_test_accuracy_score","mean_test_balanced_accuracy", 'mean_test_f1']]
dt_results

   param_criterion param_max_depth  ...  mean_test_balanced_accuracy  mean_test_f1
0             gini               5  ...                         0.69          0.51
1             gini               6  ...                         0.72          0.56
2             gini               7  ...                         0.71          0.53
3             gini               8  ...                         0.71          0.52
4             gini               9  ...                         0.70          0.50
5             gini              10  ...                         0.72          0.53
6             gini              11  ...                         0.70          0.50
7             gini              12  ...                         0.71          0.50
8             gini              13  ...                         0.72          0.52
9             gini              14  ...                         0.71          0.51
10            gini              15  ...                         0.70          0.50
11            gini              16  ...                         0.73          0.53
12            gini              17  ...                         0.72          0.52
13            gini              18  ...                         0.72          0.52
14            gini              19  ...                         0.71          0.51
15            gini              20  ...                         0.72          0.52
16            gini              21  ...                         0.71          0.50
17            gini              22  ...                         0.71          0.50
18            gini              23  ...                         0.72          0.51
19            gini              24  ...                         0.72          0.51
20            gini              25  ...                         0.72          0.51
21            gini              26  ...                         0.72          0.51
22            gini              27  ...                         0.72          0.51
23            gini              28  ...                         0.72          0.51
24            gini              29  ...                         0.72          0.51
25            gini              30  ...                         0.72          0.51
26            gini              35  ...                         0.72          0.51
27         entropy               5  ...                         0.70          0.51
28         entropy               6  ...                         0.68          0.47
29         entropy               7  ...                         0.70          0.50
30         entropy               8  ...                         0.71          0.51
31         entropy               9  ...                         0.69          0.47
32         entropy              10  ...                         0.68          0.47
33         entropy              11  ...                         0.69          0.47
34         entropy              12  ...                         0.70          0.48
35         entropy              13  ...                         0.69          0.47
36         entropy              14  ...                         0.70          0.48
37         entropy              15  ...                         0.69          0.47
38         entropy              16  ...                         0.69          0.48
39         entropy              17  ...                         0.69          0.48
40         entropy              18  ...                         0.69          0.48
41         entropy              19  ...                         0.69          0.48
42         entropy              20  ...                         0.69          0.48
43         entropy              21  ...                         0.69          0.48
44         entropy              22  ...                         0.69          0.48
45         entropy              23  ...                         0.69          0.48
46         entropy              24  ...                         0.69          0.48
47         entropy              25  ...                         0.69          0.48
48         entropy              26  ...                         0.69          0.48
49         entropy              27  ...                         0.69          0.48
50         entropy              28  ...                         0.69          0.48
51         entropy              29  ...                         0.69          0.48
52         entropy              30  ...                         0.69          0.48
53         entropy              35  ...                         0.69          0.48

[54 rows x 7 columns]

In [ ]:
dt = DecisionTreeClassifier(max_depth=13,criterion="gini",random_state=123)
dt_model = dt.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("DT:")
print("acc",accuracy_score(y_test, y_pred_dt))
print("bacc",balanced_accuracy_score(y_test, y_pred_dt))
print("precision",precision_score(y_test, y_pred_dt))
print("Sensitivity/Recall",recall_score(y_test, y_pred_dt)) # = Sensitivity
print("specificity",balanced_accuracy_score(y_test, y_pred_dt)*2-recall_score(y_test, y_pred_dt))
print("f1",f1_score(y_test, y_pred_dt))

DT:
acc 0.907185628742515
bacc 0.8246726252338392
precision 0.6923076923076923
Sensitivity/Recall 0.7058823529411765
specificity 0.9434628975265019
f1 0.6990291262135924

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_g = {
    "n_estimators": [2,3,4,5,6],
    "criterion": ["entropy","gini"],
    "max_depth": [15,16,17,18,19,20]

}

scorers_rf = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score),
    'balanced_accuracy': make_scorer(balanced_accuracy_score),
    'f1': make_scorer(f1_score)
}

skf = StratifiedKFold(n_splits=5, random_state = 549)
refit_score='recall_score'

rf_gsCV = GridSearchCV(
    RandomForestClassifier(random_state = 549),
    rf_g,
    scoring=scorers_rf,
    refit=refit_score,
    cv = skf
)

rf_gsCV.fit(X_train, y_train)
rf_results = pd.DataFrame(rf_gsCV.cv_results_)
#rf_results = rf_resutlts.sort_values(by='mean_test_precision_score', ascending=False)

In [ ]:
rf_results = pd.DataFrame(rf_gsCV.cv_results_)[["param_n_estimators","param_max_depth","param_criterion","mean_test_precision_score", "mean_test_recall_score","mean_test_accuracy_score","mean_test_balanced_accuracy", 'mean_test_f1']]
rf_results = rf_results.sort_values(by='mean_test_recall_score', ascending=False)
rf_results

   param_n_estimators  ... mean_test_f1
33                  5  ...         0.53
53                  5  ...         0.52
58                  5  ...         0.53
48                  5  ...         0.52
51                  3  ...         0.49
38                  5  ...         0.52
56                  3  ...         0.49
46                  3  ...         0.49
1                   3  ...         0.50
21                  3  ...         0.50
16                  3  ...         0.50
26                  3  ...         0.50
11                  3  ...         0.50
31                  3  ...         0.49
36                  3  ...         0.48
6                   3  ...         0.49
43                  5  ...         0.50
34                  6  ...         0.51
41                  3  ...         0.46
49                  6  ...         0.48
54                  6  ...         0.47
39                  6  ...         0.47
44                  6  ...         0.47
32                  4  ...         0.47
23                  5  ...         0.45
28                  5  ...         0.45
59                  6  ...         0.46
18                  5  ...         0.42
13                  5  ...         0.43
52                  4  ...         0.44
37                  4  ...         0.45
47                  4  ...         0.44
3                   5  ...         0.42
8                   5  ...         0.41
57                  4  ...         0.42
42                  4  ...         0.41
30                  2  ...         0.36
27                  4  ...         0.38
22                  4  ...         0.38
17                  4  ...         0.38
12                  4  ...         0.38
35                  2  ...         0.36
7                   4  ...         0.37
2                   4  ...         0.37
24                  6  ...         0.37
4                   6  ...         0.37
29                  6  ...         0.37
40                  2  ...         0.35
19                  6  ...         0.36
14                  6  ...         0.36
50                  2  ...         0.34
10                  2  ...         0.35
15                  2  ...         0.35
45                  2  ...         0.34
20                  2  ...         0.35
25                  2  ...         0.35
5                   2  ...         0.35
0                   2  ...         0.33
9                   6  ...         0.33
55                  2  ...         0.32

[60 rows x 8 columns]

In [ ]:
rf = RandomForestClassifier(n_estimators=3,criterion="gini", max_depth = 15, random_state=549)
rf_model = rf.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("RF:")
print("acc",accuracy_score(y_test, y_pred_rf))
print("bacc",balanced_accuracy_score(y_test, y_pred_rf))
print("precision",precision_score(y_test, y_pred_rf))
print("sensitivity/recall",recall_score(y_test, y_pred_rf))
print("specificity",balanced_accuracy_score(y_test, y_pred_rf)*2-recall_score(y_test, y_pred_rf))
print("f1",f1_score(y_test, y_pred_rf))

RF:
acc 0.8892215568862275
bacc 0.7337005473567519
precision 0.6842105263157895
sensitivity/recall 0.5098039215686274
specificity 0.9575971731448765
f1 0.5842696629213484

In [13]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda_g = {
    "solver": ["svd", "lsqr", "eigen"],
    "shrinkage": ["auto", None]
}

scorers_lda = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score),
    'balanced_accuracy': make_scorer(balanced_accuracy_score),
    'f1': make_scorer(f1_score)
}

skf = StratifiedKFold(n_splits=5, random_state = 549)
refit_score='recall_score'

lda_gsCV = GridSearchCV(
    LinearDiscriminantAnalysis(),
    lda_g,
    scoring=scorers_lda,
    refit=refit_score,
    cv = skf
)

lda_gsCV.fit(X_train, y_train)
lda_results = pd.DataFrame(lda_gsCV.cv_results_)

In [14]:
lda_results = pd.DataFrame(lda_gsCV.cv_results_)[["param_solver","param_shrinkage","mean_test_precision_score", "mean_test_recall_score","mean_test_accuracy_score","mean_test_balanced_accuracy", 'mean_test_f1']]
lda_results = lda_results.sort_values(by='mean_test_recall_score', ascending=False)
lda_results

  param_solver param_shrinkage  ...  mean_test_balanced_accuracy  mean_test_f1
3          svd            None  ...                         0.75          0.60
4         lsqr            None  ...                         0.75          0.60
5        eigen            None  ...                         0.75          0.60
1         lsqr            auto  ...                         0.71          0.56
2        eigen            auto  ...                         0.71          0.56
0          svd            auto  ...                          nan           nan

[6 rows x 7 columns]

In [15]:
lda = LinearDiscriminantAnalysis(solver="svd",shrinkage=None)
lda_model = lda.fit(X_train, y_train)
y_pred_lda = lda_model.predict(X_test)

print("LDA:")
print("acc",accuracy_score(y_test, y_pred_lda))
print("bacc",balanced_accuracy_score(y_test, y_pred_lda))
print("precision",precision_score(y_test, y_pred_lda))
print("Sensitivity/Recall",recall_score(y_test, y_pred_lda))
print("specificity",balanced_accuracy_score(y_test, y_pred_lda)*2-recall_score(y_test, y_pred_lda))
print("f1",f1_score(y_test, y_pred_lda))

LDA:
acc 0.9191616766467066
bacc 0.7835169403450426
precision 0.8333333333333334
Sensitivity/Recall 0.5882352941176471
specificity 0.9787985865724381
f1 0.6896551724137931

In [16]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

qda_g = {
    }

scorers_qda = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score),
    'balanced_accuracy': make_scorer(balanced_accuracy_score),
    'f1': make_scorer(f1_score)
}

skf = StratifiedKFold(n_splits=5, random_state = 549)
refit_score='recall_score'

qda_gsCV = GridSearchCV(
    QuadraticDiscriminantAnalysis(),
    qda_g,
    scoring=scorers_qda,
    refit=refit_score,
    cv = skf
)

qda_gsCV.fit(X_train, y_train)
qda_results = pd.DataFrame(qda_gsCV.cv_results_)

In [17]:
qda_results = pd.DataFrame(qda_gsCV.cv_results_)[["mean_test_precision_score", "mean_test_recall_score","mean_test_accuracy_score","mean_test_balanced_accuracy", 'mean_test_f1']]
qda_results = qda_results.sort_values(by='mean_test_recall_score', ascending=False)
qda_results

   mean_test_precision_score  ...  mean_test_f1
0                       0.57  ...          0.59

[1 rows x 5 columns]

In [18]:
qda = QuadraticDiscriminantAnalysis()
qda_model = qda.fit(X_train, y_train)
y_pred_qda = qda_model.predict(X_test)

print("QDA:")
print("acc",accuracy_score(y_test, y_pred_qda))
print("bacc",balanced_accuracy_score(y_test, y_pred_qda))
print("precision",precision_score(y_test, y_pred_qda))
print("Sensitivity/Recall",recall_score(y_test, y_pred_qda))
print("specificity",balanced_accuracy_score(y_test, y_pred_qda)*2-recall_score(y_test, y_pred_qda))
print("f1",f1_score(y_test, y_pred_qda))

QDA:
acc 0.8712574850299402
bacc 0.8115083489226079
precision 0.5606060606060606
Sensitivity/Recall 0.7254901960784313
specificity 0.8975265017667845
f1 0.6324786324786323

In [19]:
from sklearn.ensemble import StackingClassifier

estimators_list2 = [
#              ("rf", rf_model),
 #             ("dt", dt_model),
  #            ("mlp", mlp_model),
              ("lda", lda_model),
              ("qda", qda_model)
]

s_model2 = StackingClassifier(estimators = estimators_list2)#, final_estimator = mlp_model)              

s_model2.fit(X_train, y_train)
y_pred_s_model2 = s_model2.predict(X_test)

print("s_model2:")
print("acc",accuracy_score(y_test, y_pred_s_model2))
print("bacc",balanced_accuracy_score(y_test, y_pred_s_model2))
print("precision",precision_score(y_test, y_pred_s_model2))
print("Sensitivity/Recall",recall_score(y_test, y_pred_s_model2))
print("specificity",balanced_accuracy_score(y_test, y_pred_s_model2)*2-recall_score(y_test, y_pred_s_model2))
print("f1",f1_score(y_test, y_pred_s_model2))

s_model2:
acc 0.9191616766467066
bacc 0.7594055289960507
precision 0.9
Sensitivity/Recall 0.5294117647058824
specificity 0.9893992932862191
f1 0.6666666666666667